import Head from 'next/head';
import Avatar from '../components/avatar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
        <header className="flex w-full p-5 justify-between text-sm text-gray-700">
          {/* Left Section */}
          <div className="flex space-x-4 items-center">
            <p className="link">About</p>
            <p className="link">Store</p>
          </div>
          {/* Right Section */}
          <div className="flex space-x-4 items-center">
            <p className="link">Gmail</p>
            <p className="link">Images</p>
         

          {/* Icon */}

          {/* Avatar */}
            <Avatar 
              url="https://github.com/PeaceAntoHim/Frans-Portfolio-3.0/blob/main/img/FransG.png?raw=true"
            />
          </div>
        </header>
      {/* Body */}

      {/* Footer */}

    </div>
  )
}
